# Generated by Django 4.2.30 on 2026-07-29 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_department_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='assigned_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_examinations', to=settings.AUTH_USER_MODEL),
        ),
    ]
