# Generated by Django 4.2.30 on 2026-07-29 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_examination_assigned_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GEMINI', 'Google Gemini AI'), ('OPENAI', 'OpenAI GPT-4o'), ('MOCK', 'Mock Testing Provider')], default='GEMINI', max_length=20)),
                ('gemini_model_name', models.CharField(default='gemini-1.5-flash', max_length=50)),
                ('openai_model_name', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('ocr_engine', models.CharField(choices=[('PADDLE', 'PaddleOCR Primary'), ('TESSERACT', 'PyTesseract Fallback'), ('AUTO', 'Auto-Detect Hybrid')], default='AUTO', max_length=20)),
                ('preprocess_image', models.BooleanField(default=True, help_text='Enable deskewing, noise removal, and contrast enhancement.')),
                ('confidence_threshold', models.FloatField(default=0.75, help_text='Threshold below which AI marks require mandatory review.')),
                ('enable_rag_learning', models.BooleanField(default=True, help_text='Retrieve past teacher corrections as few-shot exemplars.')),
                ('prompt_template', models.TextField(blank=True, help_text='Custom prompt instructions for the evaluation engine.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField()),
                ('ai_suggested_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('teacher_final_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correction_reason', models.TextField(blank=True, help_text='Explanation for why teacher adjusted AI score.')),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Vector embedding for semantic similarity search.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='core.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_corrections', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='AIMemoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('model_version', models.CharField(max_length=50)),
                ('prompt_snapshot', models.TextField()),
                ('raw_response_json', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_memory_logs', to='core.evaluation')),
            ],
        ),
    ]
