# Generated by Django 5.2.16 on 2026-07-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aiconfiguration_feedbackcorrection_aimemorylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='gemini_model_name',
            field=models.CharField(default='gemini-flash-latest', max_length=50),
        ),
    ]
