# Generated by Django 4.2.30 on 2026-07-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aiconfiguration_gemini_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='course_outline_file',
            field=models.FileField(blank=True, help_text='Uploaded Course Syllabus / Outline document.', null=True, upload_to='course_outlines/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='examination',
            name='question_paper_file',
            field=models.FileField(blank=True, help_text='Uploaded Question Paper document or image.', null=True, upload_to='exam_questions/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='examination',
            name='rubric_file',
            field=models.FileField(blank=True, help_text='Uploaded Grading Rubric document or image.', null=True, upload_to='exam_rubrics/%Y/%m/'),
        ),
    ]
