# Generated by Django 4.2.30 on 2026-07-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_examination_course_outline_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bloom_level',
            field=models.CharField(default='Understand', help_text='Bloom Taxonomy Level', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='cea_mapping',
            field=models.JSONField(blank=True, default=list, help_text="Complex Engineering Activities (e.g. ['CEA1'])"),
        ),
        migrations.AddField(
            model_name='question',
            name='cep_mapping',
            field=models.JSONField(blank=True, default=list, help_text="Complex Engineering Problems (e.g. ['CEP1'])"),
        ),
        migrations.AddField(
            model_name='question',
            name='co_mapping',
            field=models.CharField(blank=True, help_text='Course Outcome Mapping (e.g. CO1)', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='command_verbs',
            field=models.JSONField(blank=True, default=list, help_text='Instructional verbs (e.g. Explain, Calculate, Design)'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='Medium', help_text='Easy, Medium, Hard, Very Hard', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='estimated_time',
            field=models.CharField(default='15 mins', help_text='Estimated Solving Time', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='figures',
            field=models.JSONField(blank=True, default=list, help_text='Attached Figures, Diagrams, Equations'),
        ),
        migrations.AddField(
            model_name='question',
            name='kp_mapping',
            field=models.JSONField(blank=True, default=list, help_text="Knowledge Profile (e.g. ['KP1', 'KP3'])"),
        ),
        migrations.AddField(
            model_name='question',
            name='po_mapping',
            field=models.JSONField(blank=True, default=list, help_text="Program Outcome Mappings (e.g. ['PO(a)', 'PO(c)'])"),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.JSONField(blank=True, default=list, help_text='Categories (e.g. Theory, Numerical, Algorithm, Scenario)'),
        ),
        migrations.AddField(
            model_name='question',
            name='scenario',
            field=models.TextField(blank=True, help_text='Optional case scenario or context'),
        ),
        migrations.AddField(
            model_name='question',
            name='teacher_notes',
            field=models.TextField(blank=True, help_text='Private teacher notes (not visible to students)'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='alternative_answers',
            field=models.TextField(blank=True, help_text='Alternative valid solutions'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='common_mistakes',
            field=models.JSONField(blank=True, default=list, help_text='Common student pitfalls and deductions'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='expected_answer',
            field=models.TextField(blank=True, help_text='Structured expected answer format'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Expected key terms/concepts'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='rubric_levels',
            field=models.JSONField(blank=True, default=dict, help_text='Grading levels (Excellent, Good, Average, Poor, Fail)'),
        ),
    ]
