# Generated by Django 5.2.16 on 2026-07-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_question_bloom_level_question_cea_mapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='provider',
            field=models.CharField(choices=[('GEMINI', 'Google Gemini AI'), ('GROQ', 'Groq AI (Llama-3 / Mixtral)'), ('OPENAI', 'OpenAI GPT-4o'), ('OLLAMA', 'Local Ollama LLM'), ('MOCK', 'Mock Testing Provider')], default='GEMINI', max_length=20),
        ),
    ]
