# Generated by Django 4.2.30 on 2026-08-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_aiconfiguration_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100, unique=True)),
                ('current_model', models.CharField(default='AUTO', max_length=100)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('RATE_LIMITED', 'Rate Limited (429)'), ('EXPIRED', 'API Key Expired / Unauthorized'), ('OFFLINE', 'Offline / Unavailable')], default='HEALTHY', max_length=30)),
                ('capabilities_json', models.JSONField(default=dict, help_text='Declared capabilities (vision, pdf, json, function_calling)')),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('error_count', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('table_data', models.JSONField(default=dict, help_text='JSON grid representing rows and columns')),
                ('display_order', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables_rel', to='core.question')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_latex', models.TextField(help_text='LaTeX equation representation')),
                ('is_matrix', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas_rel', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=1)),
                ('caption', models.CharField(blank=True, help_text='e.g. Figure 1: 8-bit Grayscale Matrix', max_length=255)),
                ('image', models.ImageField(upload_to='exam_figures/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='exam_figures/thumbs/%Y/%m/')),
                ('bounding_box', models.JSONField(blank=True, default=list, help_text='[xmin, ymin, xmax, ymax]')),
                ('display_order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures_rel', to='core.question')),
            ],
            options={
                'ordering': ['page_number', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elements_json', models.JSONField(default=list, help_text='Hierarchical DOM tree (headings, questions, figures, tables, boxes)')),
                ('total_pages', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_dom', to='core.examination')),
            ],
        ),
    ]
