# Generated by Django 4.2.30 on 2026-08-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aiproviderhealth_questiontable_questionformula_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiontable',
            options={'ordering': ['page_number', 'display_order', 'id']},
        ),
        migrations.AddField(
            model_name='questionformula',
            name='bounding_box',
            field=models.JSONField(blank=True, default=list, help_text='[xmin, ymin, xmax, ymax]'),
        ),
        migrations.AddField(
            model_name='questionformula',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='questionformula',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='questionformula',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exam_formulas/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='questionformula',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questiontable',
            name='bounding_box',
            field=models.JSONField(blank=True, default=list, help_text='[xmin, ymin, xmax, ymax]'),
        ),
        migrations.AddField(
            model_name='questiontable',
            name='cell_json',
            field=models.JSONField(default=list, help_text="2D array of cell text e.g. [['50','56'], ['52','72']]"),
        ),
        migrations.AddField(
            model_name='questiontable',
            name='columns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questiontable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='questiontable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exam_tables/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='questiontable',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questiontable',
            name='rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionformula',
            name='raw_latex',
            field=models.TextField(blank=True, help_text='LaTeX equation representation'),
        ),
        migrations.AlterField(
            model_name='questiontable',
            name='table_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
