# Generated by Django 4.2.30 on 2026-08-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_questiontable_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontable',
            name='element_type',
            field=models.CharField(choices=[('TABLE', 'Table'), ('MATRIX', 'Matrix'), ('GRID', 'Grid')], default='TABLE', max_length=20),
        ),
    ]
