# Generated by Django 4.2.30 on 2026-08-04 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_questiontable_element_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('maximum_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentage', models.FloatField(default=0.0)),
                ('strengths_json', models.JSONField(blank=True, default=list)),
                ('mistakes_json', models.JSONField(blank=True, default=list)),
                ('missing_points_json', models.JSONField(blank=True, default=list)),
                ('rubric_breakdown_json', models.JSONField(blank=True, default=list)),
                ('feedback_text', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Teacher Review'), ('APPROVED', 'Approved by Teacher'), ('OVERRIDDEN', 'Overridden by Teacher'), ('REJECTED', 'Rejected / Re-evaluate')], default='PENDING', max_length=20)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='Anonymous Student', max_length=200)),
                ('student_roll_no', models.CharField(blank=True, max_length=100)),
                ('script_file', models.FileField(upload_to='student_submissions/%Y/%m/')),
                ('total_obtained_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_max_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SEGMENTED', 'Answer Segmented'), ('EVALUATED', 'AI Evaluated'), ('REVIEWED', 'Teacher Reviewed & Finalized')], default='UPLOADED', max_length=30)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to='core.examination')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVE', 'Approved AI Score'), ('OVERRIDE', 'Overrode Marks'), ('REJECT', 'Rejected Score'), ('RE_EVALUATE', 'Requested AI Re-evaluation')], max_length=20)),
                ('previous_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('review_comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('evaluation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.evaluationresult')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=1)),
                ('page_image', models.ImageField(upload_to='submission_pages/%Y/%m/')),
                ('ocr_raw_text', models.TextField(blank=True)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.studentsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('bounding_box_json', models.JSONField(blank=True, default=dict)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='core.submissionpage')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_answers', to='core.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.studentsubmission')),
            ],
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='submission_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_result', to='core.submissionanswer'),
        ),
        migrations.CreateModel(
            name='EvaluationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.evaluationresult')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(max_length=255)),
                ('allocated_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('awarded_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('comments', models.TextField(blank=True)),
                ('evaluation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_feedbacks', to='core.evaluationresult')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details_json', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.studentsubmission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('attachment_file', models.FileField(upload_to='evaluation_attachments/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.evaluationresult')),
            ],
        ),
    ]
