# Generated by Django 4.2.30 on 2026-08-07 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_evaluationresult_studentsubmission_teacherreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='submission_pdfs/%Y/%m/')),
                ('page_count', models.IntegerField(default=1)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_document', to='core.studentsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.ImageField(upload_to='submission_raw_images/%Y/%m/')),
                ('processed_file', models.ImageField(blank=True, null=True, upload_to='submission_processed_images/%Y/%m/')),
                ('sequence_order', models.IntegerField(default=1)),
                ('rotation_angle', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_images', to='core.studentsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_prompt', models.TextField(blank=True)),
                ('evaluation_mode', models.CharField(default='Rubric-based', max_length=50)),
                ('strictness_level', models.CharField(default='Balanced', max_length=30)),
                ('ai_provider', models.CharField(default='GEMINI', max_length=50)),
                ('model_name', models.CharField(default='AUTO', max_length=100)),
                ('temperature', models.FloatField(default=0.2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_history', to='core.evaluationresult')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(default='EASYOCR', max_length=50)),
                ('page_confidence', models.FloatField(default=0.0)),
                ('word_boxes_json', models.JSONField(default=list, help_text='Per-word bbox, text, and confidence ratings')),
                ('line_boxes_json', models.JSONField(default=list, help_text='Per-line bbox and text')),
                ('raw_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='core.submissionpage')),
            ],
        ),
    ]
