# Generated by Django 4.2.30 on 2026-08-07 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_submissionpdf_submissionimage_prompthistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number_raw', models.CharField(help_text='Exact string detected, e.g. Q.1, (1), ১', max_length=50)),
                ('question_number_normalized', models.CharField(help_text='Normalized number string, e.g. 1, 2, 3', max_length=20)),
                ('bbox_json', models.JSONField(blank=True, default=dict, help_text='Bounding box coordinates [ymin, xmin, ymax, xmax]')),
                ('confidence', models.FloatField(default=0.0)),
                ('detection_method', models.CharField(choices=[('OCR_PATTERN', 'OCR Pattern Matching'), ('LAYOUT_POSITION', 'Layout & Position Analysis'), ('LLM_SEMANTIC', 'LLM Semantic Classification'), ('MANUAL_TEACHER', 'Manual Teacher Entry')], default='OCR_PATTERN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_detections', to='core.submissionpage')),
            ],
        ),
        migrations.CreateModel(
            name='MappingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(help_text='e.g. AUTO_DETECTED, SEMANTIC_FALLBACK, TEACHER_OVERRIDE, CONFIRMED', max_length=50)),
                ('details_json', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_history', to='core.studentsubmission')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_numbers_json', models.JSONField(default=list, help_text='Array of page numbers attached to this question answer')),
                ('confidence', models.FloatField(default=0.0)),
                ('mapping_status', models.CharField(choices=[('AUTO_HIGH', 'High Confidence Auto Match'), ('AMBIGUOUS', 'Ambiguous / Requires Teacher Review'), ('MANUAL_OVERRIDE', 'Teacher Override Confirmed')], default='AUTO_HIGH', max_length=30)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_mappings', to='core.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mappings', to='core.studentsubmission')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
