# Generated by Django 4.2.30 on 2026-08-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_questiondetection_mappinghistory_questionmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='Set to True after teacher clicks Finalize Evaluation. Triggers temp file cleanup.'),
        ),
        migrations.AddField(
            model_name='submissionimage',
            name='version',
            field=models.IntegerField(default=1, help_text='Version incremented on each image edit (rotation, crop, contrast)'),
        ),
        migrations.AddField(
            model_name='submissionimage',
            name='working_image_path',
            field=models.CharField(blank=True, help_text='Path to active working copy in submission_working/', max_length=500),
        ),
        migrations.AddField(
            model_name='submissionpage',
            name='version',
            field=models.IntegerField(default=1, help_text='Version incremented on each image edit (rotation, crop, contrast)'),
        ),
        migrations.AddField(
            model_name='submissionpage',
            name='working_image_path',
            field=models.CharField(blank=True, help_text='Path to active working copy in submission_working/', max_length=500),
        ),
    ]
