# Generated by Django 4.2.30 on 2026-08-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_studentsubmission_is_finalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PREVIEW_READY', 'Preview Ready'), ('OCR_COMPLETE', 'OCR Complete'), ('MAPPING_COMPLETE', 'Question Mapping Complete'), ('AI_EVALUATED', 'AI Evaluated'), ('TEACHER_REVIEW', 'In Teacher Review Workspace'), ('FINALIZED', 'Finalized & Locked'), ('ARCHIVED', 'Archived')], default='UPLOADED', max_length=30),
        ),
    ]
