# Generated by Django 4.2.30 on 2026-08-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_studentsubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmapping',
            name='regions_json',
            field=models.JSONField(blank=True, default=list, help_text='Array of AnswerRegion bounding box dictionaries attached to this question'),
        ),
        migrations.AddField(
            model_name='submissionpage',
            name='answer_regions_json',
            field=models.JSONField(blank=True, default=list, help_text='Detailed AnswerRegion objects for this page'),
        ),
    ]
