# Generated by Django 4.2.30 on 2026-08-25 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_questionmapping_regions_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTabulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='Spring 2026', max_length=50)),
                ('section', models.CharField(default='C', max_length=20)),
                ('weightage_config', models.JSONField(default=dict, help_text="Weightages for assessment types, e.g. {'class_test': 10, 'midterm': 25, 'final': 50, 'assignment': 10, 'attendance': 5}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabulations', to='core.course')),
            ],
            options={
                'unique_together': {('course', 'semester', 'section')},
            },
        ),
        migrations.CreateModel(
            name='StudentGradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=150)),
                ('exam_scores', models.JSONField(default=dict, help_text='Exam / Assessment breakdown per question and totals')),
                ('co_scores', models.JSONField(default=dict, help_text="Obtained marks per Course Outcome (e.g. {'CO1': 34.0, ...})")),
                ('po_scores', models.JSONField(default=dict, help_text="Obtained marks per Program Outcome (e.g. {'PO1': 230.0, ...})")),
                ('overall_score', models.FloatField(default=0.0)),
                ('letter_grade', models.CharField(default='F', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tabulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='core.coursetabulation')),
            ],
            options={
                'unique_together': {('tabulation', 'student_id')},
            },
        ),
    ]
