# Generated by Django 5.2.16 on 2026-08-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_coursetabulation_studentgraderecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
