# Generated by Django 4.2.30 on 2026-08-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_question_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='master_solution_file',
            field=models.FileField(blank=True, help_text='Uploaded Master / Benchmark Solution Script (PDF or Images)', null=True, upload_to='exam_master_solutions/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='examination',
            name='master_solution_parsed',
            field=models.BooleanField(default=False, help_text="Flag indicating whether Master Solution has been OCR'd and mapped per question."),
        ),
        migrations.AddField(
            model_name='question',
            name='master_solution_steps',
            field=models.JSONField(blank=True, default=list, help_text="Structured benchmark steps: [{'step': '1', 'desc': 'Matrix setup', 'marks': 5.0}]"),
        ),
        migrations.AddField(
            model_name='question',
            name='master_solution_text',
            field=models.TextField(blank=True, default='', help_text='Extracted step-by-step benchmark solution text for this question.'),
        ),
    ]
