# Generated by Django 4.2.30 on 2026-08-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_examination_master_solution_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfigure',
            name='is_master_solution_figure',
            field=models.BooleanField(default=False, help_text="True if this figure was extracted from the teacher's Master Benchmark Solution PDF."),
        ),
    ]
