# Generated by Django 5.2.16 on 2026-08-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_is_master_solution_figure_to_questionfigure'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='extracted_ocr_data',
            field=models.JSONField(blank=True, default=dict, help_text='Cached OCR text per page: {"page_1": "...", "page_2": "..."}'),
        ),
    ]
