# Generated by Django 5.2.16 on 2026-08-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_extracted_ocr_data_to_studentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PREVIEW_READY', 'Preview Ready'), ('WORKING_COPY_CREATED', 'Working Copy Created'), ('PDF_GENERATED', 'PDF Generated'), ('OCR_COMPLETE', 'OCR Complete'), ('SEGMENTED', 'Answer Segmented'), ('MAPPING_COMPLETE', 'Question Mapping Complete'), ('WAITING_TEACHER_CONFIRMATION', 'Waiting for Teacher Confirmation'), ('AI_EVALUATED', 'AI Evaluated'), ('UNDER_REVIEW', 'Under Teacher Review'), ('REVIEWED', 'Teacher Reviewed'), ('FINALIZED', 'Finalized & Locked'), ('ARCHIVED', 'Archived'), ('FAILED', 'Evaluation Failed')], default='UPLOADED', max_length=30),
        ),
    ]
