# Generated by Django 5.2.16 on 2026-08-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_studentsubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgraderecord',
            name='attendance_marks',
            field=models.FloatField(default=5.0, help_text='Attendance score out of 5.0 (5% weightage)'),
        ),
        migrations.AddField(
            model_name='studentgraderecord',
            name='is_manually_edited',
            field=models.BooleanField(default=False, help_text='Flag indicating manual overrides from the instructor'),
        ),
    ]
