# Generated by Django 5.2.16 on 2026-08-30 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_studentgraderecord_attendance_marks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evaluationresult',
            index=models.Index(fields=['status', 'requires_manual_review'], name='core_evalua_status_1f634b_idx'),
        ),
        migrations.AddIndex(
            model_name='questionmapping',
            index=models.Index(fields=['submission', 'mapping_status'], name='core_questi_submiss_f91196_idx'),
        ),
        migrations.AddIndex(
            model_name='questionmapping',
            index=models.Index(fields=['submission', 'is_confirmed'], name='core_questi_submiss_87e971_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgraderecord',
            index=models.Index(fields=['tabulation', 'student_id'], name='core_studen_tabulat_26637b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgraderecord',
            index=models.Index(fields=['tabulation', 'overall_score'], name='core_studen_tabulat_3643a4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgraderecord',
            index=models.Index(fields=['is_manually_edited'], name='core_studen_is_manu_4bbc48_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubmission',
            index=models.Index(fields=['examination', 'status'], name='core_studen_examina_acdee2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubmission',
            index=models.Index(fields=['student_roll_no'], name='core_studen_student_63d99e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubmission',
            index=models.Index(fields=['is_finalized'], name='core_studen_is_fina_8704af_idx'),
        ),
    ]
